name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [2.7, 3.0, 3.9]
        python-version: [3.7.17, 3.8.18, 3.9.19, 3.10.14, 3.11.9, 3.12.3, 3.13.0-beta.1, pypy-3.9, graalpy-24.0]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --durations=0 --verbosity=5 -r A --showlocals --full-trace test.py
